// Generated by https://quicktype.io

export interface AxiosResponse {
  data: Data;
  status: number;
  statusText: string;
  headers: AxiosResponseHeaders;
  config: Config;
  request: Request;
}

export interface Config {
  transitional: Transitional;
  adapter: string[];
  transformRequest: null[];
  transformResponse: null[];
  timeout: number;
  xsrfCookieName: string;
  xsrfHeaderName: string;
  maxContentLength: number;
  maxBodyLength: number;
  env: Request;
  headers: ConfigHeaders;
  method: string;
  url: string;
  data: string;
}

export interface Request {}

export interface ConfigHeaders {
  Accept: string;
  "Content-Type": string;
}

export interface Transitional {
  silentJSONParsing: boolean;
  forcedJSONParsing: boolean;
  clarifyTimeoutError: boolean;
}

export interface Data {
  user_name: string;
  email: string;
  password: string;
  auth_strategy: null;
  id: number;
  created_at: string;
}

export interface AxiosResponseHeaders {
  "content-length": string;
  "content-type": string;
}

// Generated by https://quicktype.io

export interface ResponseExample {
  message: string;
  status: number;
  data: Data;
}

export interface Data {
  user_name: string;
  email: string;
  password: string;
  auth_strategy: null;
  id: number;
  created_at: string;
}

export interface FormSingUpEnum {
  handleChangeLogin: () => void;
}

export interface FormLoginEnum {
  handleOpenModal: () => void;
}
